spring:
  application:
    name: membership
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

  redis:
    host: localhost
    port: 6700
    password: redis
    timeout: 3000

server:
  port: 18017

dubbo:
  scan:
    base-packages: membership.api
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 28094
  consumer:
    check: false
  provider:
    threads: 800
    actives: 200
